### ISSUE TITLE
Potential build issues with Pods

### ISSUE THREAD

**Issue by jasonify** [SoftwareEngineeringDaily/se-daily-iOS#10]
It seems I might not be the only one experiencing this. Here is what I get on a fresh pull from github: 

```$ pod install
Analyzing dependencies
[!] The version of CocoaPods used to generate the lockfile (1.4.0.beta.1) is higher than the version of the current executable (1.3.1). Incompatibility issues may arise.
[!] Unable to satisfy the following requirements:

- `KoalaTeaPlayer` required by `Podfile`
- `KoalaTeaPlayer (= 0.1.4)` required by `Podfile.lock`

None of your spec sources contain a spec satisfying the dependencies: `KoalaTeaPlayer, KoalaTeaPlayer (= 0.1.4)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

[!] Smart quotes were detected and ignored in your Podfile. To avoid issues in the future, you should not use TextEdit for editing it. If you are not using TextEdit, you should turn off smart quotes in your editor of choice.

[!] Automatically assigning platform ios with version 10.3 on target SEDaily-IOS because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
$ open .
```

After deleting the Podfile.lock (and Pods directory) I get something more like this:

```
$ pod install
Analyzing dependencies
Downloading dependencies
Installing ActiveLabel (0.7.1)
Installing Alamofire (4.5.1)
Installing Crashlytics (3.8.6)
Installing Eureka (4.0.0)
Installing Fabric (1.6.13)
Installing IQKeyboardManagerSwift (5.0.2)
Installing KTResponsiveUI (0.2.2)
Installing Kingfisher (4.1.0)
Installing KoalaTeaFlowLayout (0.3.0)
Installing KoalaTeaPlayer (0.1.3)
Installing ObjectMapper (3.0.0)
Installing Pageboy (2.0.0)
Installing PureLayout (3.0.2)
Installing Realm (2.10.2)
Installing RealmSwift (2.10.2)
Installing Reusable (4.0.0)
Installing SideMenu (3.0.2)
Installing SnapKit (4.0.0)
Installing SwiftIcons (1.5.1)
Installing SwifterSwift (4.0.0)
Installing SwiftyBeaver (1.4.2)
Installing SwiftyJSON (3.1.4)
Installing Tabman (1.0.2)
Installing UIFontComplete (2.0.1)
Installing XLPagerTabStrip (7.0.0)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 22 dependencies from the Podfile and 25 total pods installed.

[!] Smart quotes were detected and ignored in your Podfile. To avoid issues in the future, you should not use TextEdit for editing it. If you are not using TextEdit, you should turn off smart quotes in your editor of choice.

[!] Automatically assigning platform ios with version 10.3 on target SEDaily-IOS because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
```

Once in Xcode I get something like this (Doing  Project->Clean seems to solve these 3) : 
```
diff: /Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

```

Many more errors (16), with ActiveLabel:
```
Property cannot be marked @IBInspectable because its type cannot be represented in Objective-C
```

```
/Users/jasonbautista/playground/sed/se-daily-iOS/Pods/ActiveLabel/ActiveLabel/ActiveLabel.swift:309:20: 'NSFontAttributeName' has been renamed to 'NSAttributedStringKey.font'

```

```

/Users/jasonbautista/playground/sed/se-daily-iOS/Pods/UIKit.NSFontAttributeName:4:12: 'NSFontAttributeName' was obsoleted in Swift 3

```

Have tried:
Opening the SEDaily-IOS.xcworkspace   and building as is
Deleting: Pods, Podfile.lock, SEDaily-IOS.xcworkspace  -> pod install 
Building Clean 
Xcode 9.1 beata +  Xcode 9.0 
Tried upgrading ActiveLabel pod, 
Tried commenting out ActiveLabel Pod from Podfile, Xcode moves to similar problems with another Pod (i.e *SwiftIcons icons 33 issues*) 

## Have yet to try:
[ ] upgrade pods to 1.4.0.beta.1
[ ] wondering if we make a branch / fork with a working Pods/ directory checked in and seeing if we can build from that? Just a random guess.

**Comment by themisterholliday** [comment]
Hey Jason, could you try again with this branch for me: 
https://github.com/SoftwareEngineeringDaily/se-daily-iOS/tree/fix-cocoa-pods-errors

And do these steps with the added `cocoapods --pre` command:

Clone the repo and then run:
```
$ sudo gem install cocoapods --pre
$ pod install
```
Open the SEDaily-IOS.xcworkspace.
```
$ open SEDaily-IOS.xcworkspace
```

**Comment by jasonify** [comment]
Some progress. It kinda works :) 

After having done that I still kept getting weird errors.  Got it running finally though. 




Here is some more info, my pods seem to think they are 1.3.1 even when starting a new bash session:
```
$ which pod
/Users/jasonbautista/.rvm/gems/ruby-2.2.5/bin/pod
```

Maybe this way of asking for pod version is incorrect:

````
 gem which cocoapods
/Users/jasonbautista/.rvm/gems/ruby-2.2.5@global/gems/cocoapods-1.4.0.beta.1/lib/cocoapods.rb
$ pod --version
1.3.1
````

So I had to delete the .xcworkspace, removing the Podlock file and Pods/. Ran pod install again.


Error now is just this (but commenting it out for now, will look into it later) AudioViewManager.swift:
```
assetPlaybackManager?.changePlayerPlaybackRate(to: newRate)
```

```
Value of type 'AssetPlayer' has no member 'changePlayerPlaybackRate'
```

**Comment by themisterholliday** [comment]
Your pod version should be `cocoapods-1.4.0.beta.1` after running `sudo gem install cocoapods --pre`.

Also try using `pod update` to get KoalaTeaPlayer to version 0.1.5.
In the command line you should see `Using KoalaTeaPlayer (0.1.5)`
That will fix the latter issue.

**Comment by themisterholliday** [comment]
Scratch that last comment. 
I fixed the libraries that were causing the issue. They were built in the CocoaPods beta accidentally.

Your pod version should be `1.3.1` and if you pull [this branch](https://github.com/SoftwareEngineeringDaily/se-daily-iOS/tree/fix-cocoa-pods-errors) again and run `pod update`, everything should build now.

**Comment by jasonify** [comment]
Works great now :)

I think we can close this issue. Maybe we just need to merge this into master if it's not there already.

**Comment by tonkatsu7** [comment]
She builds!
