### ISSUE TITLE
Audio player appears as blank after a podcast episode is done downloading 

### ISSUE THREAD

**Issue by jasonify** [SoftwareEngineeringDaily/se-daily-iOS#100]
In the current version of the app it fills in the episode that was just downloaded into the player but now it appears blank + unresponsive. Tracking it down, I  believe it was introduced when we refactored the player  [here](https://github.com/SoftwareEngineeringDaily/se-daily-iOS/commit/00c27663de21bd27a898d51e511921169b5882b1).

**Comment by justinctlam** [comment]
What are the repro steps? What about a screen shot of the issue?

**Comment by justinctlam** [comment]
Should we close this?
