### ISSUE TITLE
Player auto-playing and also dissapearing

### ISSUE THREAD

**Issue by jasonify** [SoftwareEngineeringDaily/se-daily-iOS#112]
".The TestFlight feedback included screenshots. 

In the Feed section I was playing an episode, then paused it and switched to another app. When I entered the app again, through TestFlight I believe, audio started playing on it’s own, despite there being no player controls or selected episode. 

I waited to hear something that indicated which episode was playing. It turned out to be the 05/23/2018 episode “Uber’s Data Platform With Zhenxiao Luo.” When I clicked on it, the audio continued but still there were no player controls and the appearance of the Play button seemed to indicate that nothing was playing. Only when I hit Play did the controls become visible."

**Comment by justinctlam** [comment]
I can't reproduce, are you able to reproduce on the develop branch?

**Comment by jasonify** [comment]
I saw it randomly today on the production app. I started playing a podcast, then I tapped the x to dismiss and stopped. Switched away to the feed/forum. Then I went to another app. When I came back it started playing the audio but there was no player shown.
