### ISSUE TITLE
[Enhancement] Login screen redesign

### ISSUE THREAD

**Issue by thedc89** [SoftwareEngineeringDaily/se-daily-iOS#114]
I feel like login screen may need some redesign. I would slightly modify the usage of colors and buttons shape and position.

For instance, when Sign Up is tapped on iPhone 4,7", the cancel button goes beyond the bottom edge of the screen. I know there's a scrollView there, but I believe I could redesign a bit this entire view and implement it accordingly.

My proposal

![sed design](https://user-images.githubusercontent.com/4841004/42313639-85d2985c-8043-11e8-8dd5-8004a8294d68.png)

**Comment by justinctlam** [comment]
That definitely looks nice! Will you need help implementing the design?

**Comment by thedc89** [comment]
@justinctlam Thank you very much! Help is not needed, actually, I wanted to do my first contribution to this repo by implementing it all by myself :) Thanks for asking!

The final version of the implemented restyled login:
![sedaily](https://user-images.githubusercontent.com/4841004/42439714-ec089414-8363-11e8-84a6-f5858f4d77f9.png)

**Comment by thedc89** [comment]
@crablar Do you mind sharing your opinion? I'm curious whether you think such a redesign might improve the user experience.

**Comment by crablar** [comment]
@thedc89 this looks beautiful!

I completely agree. CC @jasonify
