### ISSUE TITLE
Player loses the listener's place in the episode

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/se-daily-iOS#116]
Feedback I received: "If I switch back to the app after a day of not using it then it loses my place and episode I was listening to."

**Comment by webern** [comment]
Similar issue here, but maybe not exactly the same. If I was listening when I last used the app, I want the app to return to that exact view/context. I had to search through episodes, find the one I had been listening to, and then press play.

When I found the episode, it appeared as though the playhead was at 0, but when I played it the playhead actually jumped to where I left off.

But the main thing is to make it effortless for the user to start playing right where they left off.
