### ISSUE TITLE
[Feature] Have an option to delete cache

### ISSUE THREAD

**Issue by justinctlam** [SoftwareEngineeringDaily/se-daily-iOS#12]
It might be a good idea to have some UI to allow users to delete the cached items. It allows users to deleted unused data to save some space and help fix potential errors in the database.

**Comment by themisterholliday** [comment]
This will probably be next on the list after changing the data models a bit. I'll lay this out in a board soon as well.

**Comment by TheHollidayInn** [comment]
I think pull to refresh should fix this. Also, I believe we have removed cache/updated the cache system?

**Comment by justinctlam** [comment]
We don't have pull to refresh, it only refreshes one a day.  Yeah, if we removed the cache, then this is a nop then.
