### ISSUE TITLE
[Bug] App appears to hang after pressing play

### ISSUE THREAD

**Issue by justinctlam** [SoftwareEngineeringDaily/se-daily-iOS#14]
The time between pressing the play button and audio playing can make the app appear to hang. Suggest some UI to indicate that the audio is downloading.

**Comment by themisterholliday** [comment]
Are you talking about the latest build on the app store or the build on GitHub now? This should be fixed in the master branch. 

Also I'm seeing about getting more people into our TestFlight beta's so you can test on your phone.

**Comment by justinctlam** [comment]
This is the App Store version. I haven’t been able to get the debug build into my phone yet.
