### ISSUE TITLE
[Improvement] Add support for localization

### ISSUE THREAD

**Issue by justinctlam** [SoftwareEngineeringDaily/se-daily-iOS#17]
We may not be supporting any language other than English at the moment but we should build the app in anticipation that we should. This means any user facing strings should use NSLocalizedString. Doing it now would be easier than doing it later.

**Comment by eddies5** [comment]
After https://github.com/SoftwareEngineeringDaily/se-daily-iOS/pull/19 gets merged in, is there any work left to be done for this issue? I'm interested in taking a crack at anything left todo here.

**Comment by themisterholliday** [comment]
I just opened this [issue](https://github.com/SoftwareEngineeringDaily/se-daily-iOS/projects/1#card-5000825). It's the only thing I can think of right now while I'm restructuring the app to MVVM.
