### ISSUE TITLE
[Improvement] Seek from Lock Screen/Control Center

### ISSUE THREAD

**Issue by okwolf** [SoftwareEngineeringDaily/se-daily-iOS#25]
When playing an episode from the app, the Lock Screen/Control Center shows the current playback position, but doesn't allow for seeking in the content:
![img_5302](https://user-images.githubusercontent.com/3735164/31577678-fb4973cc-b0c7-11e7-92fe-4cac725c76be.PNG)

By contrast, Podcasts.app does allow for seeking outside the app:
![img_5303](https://user-images.githubusercontent.com/3735164/31577719-7ee13d46-b0c8-11e7-8e70-500ce69b9996.PNG)

**Comment by themisterholliday** [comment]
I believe this is as easy as `remoteCommandManager.toggleChangePlaybackPositionCommand(true)` in the AudioViewManager. I'll throw it into my next branch.

**Comment by themisterholliday** [comment]
Addressed in this pull request: https://github.com/SoftwareEngineeringDaily/se-daily-iOS/pull/29
