### ISSUE TITLE
[Enhancement] Unit tests

### ISSUE THREAD

**Issue by okwolf** [SoftwareEngineeringDaily/se-daily-iOS#26]
Right now `SEDaily-IOSTests` appears to be the standard empty project that Xcode creates. Are there plans to put some meat on these bones soon, or in the future?

**Comment by themisterholliday** [comment]
Yes. I'd like to use Quick and Nimble for tests very soon. Right now I'm fixing some architecture and making things easier to setup tests for.

**Comment by TheHollidayInn** [comment]
We now have API tests. Does anyone have suggestions for Swift test coverage? I use `coveralls` at work, but not sure if it applies for Swift.
