### ISSUE TITLE
[Feature] Offline Downloads

### ISSUE THREAD

**Issue by themisterholliday** [SoftwareEngineeringDaily/se-daily-iOS#31]

**Comment by andrewmarklloyd** [comment]
Is there any progress on this?

**Comment by TheHollidayInn** [comment]
Yea, Craig is working on this right now.

**Comment by andrewmarklloyd** [comment]
Awesome, I know I keep harping on it. At first because I want to use the feature, but now also I'm thinking about how we'll handle sending events and/or queuing them up until the user is back online.

**Comment by TheHollidayInn** [comment]
No worries! It is an important feature for sure
