### ISSUE TITLE
[Feature] Add share buttons

### ISSUE THREAD

**Issue by themisterholliday** [SoftwareEngineeringDaily/se-daily-iOS#34]

**Comment by JoeyCarson** [comment]
Hi @themisterholliday, I haven't contributed before, but I've got UIKit experience and have read up on the subject.  I'd love to give this a shot.  Any objections?  Is anyone else already working on it?  Do we have any idea of what services this should be shared to?

**Comment by themisterholliday** [comment]
No objections here! I don't believe anyone is working on this yet. 

For services I'm thinking Facebook and Twitter to start. Definitely open to any popular social medias.

**Comment by JoeyCarson** [comment]
Cool!  I've got a working prototype so far.  It's inside HeaderView.swift, though I will probably refactor it into its own class so that it can be reused other places.
