### ISSUE TITLE
[Bug] Podcast description doesn't contain links

### ISSUE THREAD

**Issue by justinctlam** [SoftwareEngineeringDaily/se-daily-iOS#49]
For example, the latest podcast on load balancing should have a clickable link to the blog post on the text "blog post about load balancing at scale"

**Comment by justinctlam** [comment]
Current style:
![oldcomp](https://user-images.githubusercontent.com/18654586/33225131-deffa658-d126-11e7-91aa-514930cae1f6.jpg)

New propose style:
![newcomp](https://user-images.githubusercontent.com/18654586/33225132-e076ee7e-d126-11e7-88f6-8c63231106dd.jpg)

I tried using a WKWebView and embed the header view into the web view's scrollview. Then I pruned some html and added some other html styling to mimic the old look. 

Links will also open up into Safari as well.

**Comment by crablar** [comment]
Much better!

**Comment by justinctlam** [comment]
I have a PR out for this, do we want these changes? There are also a few other PRs that needs some attention...

**Comment by themisterholliday** [comment]
Yep we want these changes. I'll be going through the PRs soon, no need to worry.
