### ISSUE TITLE
[Feature] Comments Support

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/se-daily-iOS#53]
This is a significant feature, so probably worth discussing with @themisterholliday if you are interested in taking it on.

The backend endpoints for this are already written.

The picture below shows several new features we want to build eventually. One idea for the comments interface is in the center.

The "related links" feature is also there. You can see [the web version of these features live today](https://www.softwaredaily.com/#/post/5a0eb57b2e7b9f000485d41d).

AMA is also in this picture, but we are not working on AMA yet.

![mobile designs 11-3-17](https://user-images.githubusercontent.com/1283090/33453466-8a75ad32-d5ca-11e7-944b-fd4ba9d3e156.png)

**Comment by justinctlam** [comment]
I built this exact feature at work. I can mentor anyone who wants to take it on.
Who owns the rest API surface for this?

**Comment by crablar** [comment]
@jasonify owns the comments API, I have a decent grasp of it too.

**Comment by justinctlam** [comment]
Is it documented somewhere?

**Comment by crablar** [comment]
https://software-enginnering-daily-api.herokuapp.com/api/docs/#/comment/get_posts__postId__comments

**Comment by jasonify** [comment]
Also note how to pass a "parent comment" when created nested comments: https://github.com/SoftwareEngineeringDaily/software-engineering-daily-api/blob/develop/server/controllers/comment.controller.js#L58

We are only nesting one level deep, so not super threaded comments.

**Comment by jasonify** [comment]
@justinctlam  Most likely I will be taking this feature on and would appreciate your mentorship :)

**Comment by justinctlam** [comment]
@jasonify for sure, let me know how I can help

**Comment by TheHollidayInn** [comment]
Fixed in #97
