### ISSUE TITLE
[Feature] Related Links Support

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/se-daily-iOS#54]
This is a significant feature, so probably worth discussing with @themisterholliday if you are interested in taking it on.

The backend endpoints for this are already written.

The picture below shows several new features we want to build eventually. One idea for the related links interface is in the center.

The "comments" feature is also there. You can see [the web version of these features live today](https://www.softwaredaily.com/#/post/5a0eb57b2e7b9f000485d41d).

AMA is also in this picture, but we are not working on AMA yet.

![mobile designs 11-3-17](https://user-images.githubusercontent.com/1283090/33453466-8a75ad32-d5ca-11e7-944b-fd4ba9d3e156.png)

**Comment by TheHollidayInn** [comment]
Fixed in #97
