### ISSUE TITLE
Player loses my place in the episode when switching audio apps

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/se-daily-iOS#57]
Steps to reproduce:
-play an episode on SED
-open a different audio app (Overcast) and play something; or kill the SED app
-come back to SED
-episode progress not there

Suggested fix:
-checkpoint the currently playing episode every 5 secon
-whenever someone switches to the app, or the app starts, load the checkpoint

**Comment by TheHollidayInn** [comment]
This is the same feature request as https://github.com/SoftwareEngineeringDaily/SEDaily-Android/issues/14

**Comment by bpirvu** [comment]
This feature is badly needed in order for the app to be really useful.

We also need this in order to be able to continue an episode from the last checkpoint after running another episode within the SED app.

**Comment by TheHollidayInn** [comment]
Agreed. I can work on this after I finish bookmarks on Android if no one else takes it up.
