### ISSUE TITLE
[Feature] - Maintain preference for player speed

### ISSUE THREAD

**Issue by seanfalconer80** [SoftwareEngineeringDaily/se-daily-iOS#62]
Each time I play an episode, I have to set my player speed for 1.6x. It would be nice if this type of preference was stored and set automatically each time I play a new episode.

**Comment by bpruss** [comment]
I'm new to contributing to open source software.  I was looking for a button to vote for this feature, and not seeing one, I am leaving this comment.

**Comment by justinctlam** [comment]
Submitted a PR for this: https://github.com/SoftwareEngineeringDaily/se-daily-iOS/pull/63
