### ISSUE TITLE
Just For You tab issue?

### ISSUE THREAD

**Issue by berkmolla** [SoftwareEngineeringDaily/se-daily-iOS#66]
The Just For You tab continuously displays a skeleton collection view for me - is this intended behaviour? I would expect it to either be empty (with a message) or showing a properly populated collection view, of course. 

Just wanted to check before digging into the code

**Comment by crablar** [comment]
Are you on the beta version? Sometimes the staging server is slow.

I am in prod and the Just For You is actually showing the same as Most Viewed...

I added Jason--but I wouldn't worry too much about this. We plan to change the episode recommendation engine. I don't think the current system is very effective (we are just using Raccoon and need to build our own).

**Comment by berkmolla** [comment]
Ah yeah I was running it through XCode, but the other tabs seem to work fine, which is why it seemed odd / like a regression. I realise these GitHub issues are more for the live version of the app so is there somewhere I can put the 'internal' ones?

**Comment by TheHollidayInn** [comment]
I think Github is fine for posting issues that are live or on develop. If you are on develop and the issue is appearing, we should definitely check it out.

**Comment by TheHollidayInn** [comment]
This seems cleared up. Feel free to open if there is another report.
