### ISSUE TITLE
[BUG] Feeds are not always loading 

### ISSUE THREAD

**Issue by jasonify** [SoftwareEngineeringDaily/se-daily-iOS#7]
Note: iOS 11.1 

It seems that on first load (after the spinner is finished) there will be a blank view, this is fixed after navigating away from this view. Going from Open Source and then back to Machine learning will fix this.

![img_1023](https://user-images.githubusercontent.com/150265/31123020-15ea905e-a7f3-11e7-8af1-d7e4eed0cdc3.PNG)

**Comment by themisterholliday** [comment]
This is an issue with using Realm coupled so closely to the UI. We're relying on Realm Fine Grained Notifications too much here and the UI isn't always updating properly. 

This will be addressed with a new repository pattern I have laid out just not implemented.

**Comment by themisterholliday** [comment]
This is addressed in this pull request: https://github.com/SoftwareEngineeringDaily/se-daily-iOS/pull/29
