### ISSUE TITLE
[Enhancement] Not clear what episodes have been downloaded or played

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/se-daily-iOS#8]
User requested "better listings of episodes that have been downloaded, how much they have been heard"

**Comment by gm2211** [comment]
This is especially true when you are not signed in:

1. I download the app
1. I'm not signed in and download a few episodes
1. I sign in and I can't find any of my downloaded episodes anywhere

Minimal improvement would be to hydrate the "Saved" page based on downloaded content on sign-in.

**Comment by crablar** [comment]
@gm2211 Agreed. We are working on some improvements to the web interface right now, after that we are going to improve iOS design! https://findcollabs.com/project/TQQCLSL2KYLq9jS7gxBq

Thank you for feedback and any more would be appreciated.
