### ISSUE TITLE
Add downloads page

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/se-daily-iOS#84]
User made this comment on Twitter:
The app should let me navigate in offline mode, if I don't have an internet connection is impossible to listen to podcasts that I downloaded.

**Comment by TheHollidayInn** [comment]
I'm changing this to add downloads page. I've seen a few requests for users to view and manage their downloads. I think an easy way to support these requests is to have a downloads page that can also be viewed offline.

**Comment by crablar** [comment]
@TheHollidayInn @jasonify What should this design be?

One idea is replace "Bookmarks" tab with "Saved" tab and episodes can either be bookmarked, saved, or both.

**Comment by TheHollidayInn** [comment]
I'd just add another tab called "Queue" that displays the downloads. The tab controller will push bookmarks into the "More" section on smaller devices and display it on large ones.

**Comment by justinctlam** [comment]
Is this being worked on? Is there a way to know which issues are being worked on to avoid duplicate work?

**Comment by themisterholliday** [comment]
This is being worked on. Yes I'll add some labels to issues.
