### ISSUE TITLE
Bookmarks don't seem to be showing even after refresh 

### ISSUE THREAD

**Issue by jasonify** [SoftwareEngineeringDaily/se-daily-iOS#90]
Saw them work once but seems to not work now.

**Comment by TheHollidayInn** [comment]
This is working on live. Are you talking about local dev?

**Comment by jasonify** [comment]
Yeah I am. I wonder if it got introduced recently

**Comment by TheHollidayInn** [comment]
Are you using develop branch?

**Comment by jasonify** [comment]
No it's something I must have introduced on my forum branch 👎  
What's weird is I'm seeing it flash and then go away.. 
I'll close this.

**Comment by jasonify** [comment]
I think I know the issue now and see why it's flashing like that.
