### ISSUE TITLE
Kept seeing the "Hello! Enjoying the SEDaily App" after clicking No? 

### ISSUE THREAD

**Issue by jasonify** [SoftwareEngineeringDaily/se-daily-iOS#96]
Happened every time I would go into an episode and went back to episode list. Something to watch out for.

Was testing on `audioview` PR:  https://github.com/SoftwareEngineeringDaily/se-daily-iOS/pull/95

<img width="331" alt="screen shot 2018-05-17 at 1 56 58 am" src="https://user-images.githubusercontent.com/150265/40167584-4372f8ce-5976-11e8-86e4-78e5029564eb.png">

**Comment by justinctlam** [comment]
I think that's how it has been designed.

Whenever the tab view controller appears it will try to show the review prompt:

```
   override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        setupNavBar()

        AskForReview.tryToExecute { didExecute in
            if didExecute {
                self.askForReview()
            }
        }
    }
```

And the conditions is that it will show 3 times max before disappearing completely.

```
        minEventsRequired = 3
        minSecondsSinceFirstEvent = 86_400 // seconds in one day
        maxExecutionsPermitted = 3
        customConditions = {
            let defaults = UserDefaults.standard
            return !(defaults.object(forKey: completedReviewKey) != nil &&
                defaults.bool(forKey: completedReviewKey))
        }
```

**Comment by themisterholliday** [comment]
Yep looks like we'll need to use `minSecondsSinceLastEvent` with the WaitForIt library. Shouldn't block #95 since it wasn't caused by anything new.
